// FROZEN CONTRACT. Do not edit this file. Every lane codes against it.
// If you believe it is wrong, say so in your handoff note instead of changing it:
// a change here breaks the other three branches silently.

export type StepStatus =
  | "pending" | "running" | "done" | "waiting_human"
  | "committed" | "rejected" | "failed" | "blocked";

export type StepKind = "reversible" | "commit";

export type LedgerStatus =
  | "proposed" | "approved" | "committed" | "rejected" | "failed" | "outcome_unknown";

export interface Step {
  id: string;                 // "5-send-customer-update"
  name: string;
  kind: StepKind;
  tool?: string;
  status: StepStatus;
  output?: string;            // drafts live here, never in model memory
  classifiedBy: "model" | "allowlist_override";
}

export interface LedgerEntry {
  idempotencyKey: string;     // `${woId}:${stepId}:${tool}:${sha256(args)}`
  tool: string;
  args: unknown;
  status: LedgerStatus;
  approvedBy?: string;
  externalId?: string;        // ONLY the committer writes this (invariant 3)
  attemptedAt?: string;
  committedAt?: string;
}

export interface WorkOrder {
  id: string;                 // "WO-1842"
  scenario: string;
  threadRef: string;          // hashed conversationKey; see D17
  constraints: string[];      // extracted, shown on every approval card
  approvers: string[];        // Slack user IDs. authorization, not decoration
  steps: Step[];
  commits: LedgerEntry[];
}

/**
 * Invariant 2. Any tool named here is forced to kind "commit" regardless of what the
 * model classified it as, and the override is logged with classifiedBy
 * "allowlist_override". The model must never be able to grant itself send access.
 */
export const COMMIT_TOOLS: ReadonlySet<string> = new Set([
  "mail.send",
  "crm.update",
  "calendar.invite",
  "esign.send",
]);

/** What every tool returns. A missing id means the outcome is unknown, not a failure. */
export interface ToolResult {
  id?: string;
}

export type ToolFn = (args: unknown) => Promise<ToolResult>;

/** Errors the Slack layer must render as cards rather than crash on. */
export class NotAuthorizedError extends Error {
  constructor(public actor: string, public approvers: string[]) {
    super("not_authorized_to_approve");
    this.name = "NotAuthorizedError";
  }
}
export class NotApprovedError extends Error {
  constructor() {
    super("not_approved");
    this.name = "NotApprovedError";
  }
}

export interface CommitResult {
  /** true when this call returned an existing receipt instead of acting (invariant 4). */
  reused: boolean;
  status: LedgerStatus;
  externalId?: string;
  idempotencyKey: string;
}
